### ISSUE TITLE
Using typescript path aliases, eg. @app on the server break eden treaty typing.

### ISSUE THREAD

**Issue by IOnlyNeedParenthesis** [elysiajs/eden#110]
Hello,
I have been developing on a monorepo with elysia.
When using the eden treaty, route parameters are type hinted as any instead of the expected types.
We have narrowed it down to being a path aliasing issue.

See this repository for a reproduction https://github.com/IOnlyNeedParenthesis/elysia-eden-treaty-repro.
This seems to be the same issue as in #99 and possibly related to #42.

**Comment by Ripwords** [comment]
I'm not sure if it's necessarily an Elysia issue. The workaround is just to simply update your frontend and backend tsconfig.json

## Frontend
```json
"references": [
    {
      "path": "../backend"             // Add reference to the backend tsconfig
    }
  ]
```

## Backend
```json
 "compilerOptions": {
    /* Visit https://aka.ms/tsconfig to read more about this file */

    /* Projects */
    // "incremental": true,                              /* Save .tsbuildinfo files to allow for incremental compilation of projects. */
    "composite": true,                                    // Enable this line
    ...
}
```

**Comment by IOnlyNeedParenthesis** [comment]
Hey @Ripwords, your solution solves the issue.
Thanks a lot.
