### ISSUE TITLE
[FEATURE REQUEST] Transform function configuration

### ISSUE THREAD

**Issue by itsyoboieltr** [elysiajs/eden#16]
It would be nice if Eden Treaty allowed for the transformation of the response.

Proposed API:

```ts
const api = edenTreaty<App>('', {
  transform: (response) => {
    if (response.error) throw response.error;
    return response.data;
  },
});

const data = await api.get();
```

Current workaround, which needs to be coded manually for each request:

```ts
const api = edenTreaty<App>('');

const response = await api.get();
if (response.error) throw response.error;
const data = response.data;
```

--- Why would this be useful? ---

Lot of current querying libraries like Tanstack query, SWR, depend on errors being thrown, so they can be returned by the hook used for querying. Eden Treaty does not throw, but returns errors and data objects, which is fine, but there should be  a way to configure the transformation of the response for these use-cases on the client level. Is this something that would be feasible to implement? @SaltyAom

**Comment by SaltyAom** [comment]
Interesting, this should be implemented.

If you have more thoughts to share about DX, and what we are missing in general.
You can share your thought here.

I'll implement this with Elysia 0.7

**Comment by itsyoboieltr** [comment]
@SaltyAom was this implemented as part of the 0.7 update? I cannot find anything about it as of yet. Maybe it is too early to ask :)

**Comment by SaltyAom** [comment]
[aa8176b](https://github.com/elysiajs/eden/commit/aa8176b2b7b6c0a7bc615fd5f224ef6b2d6a4704), published on 0.7.4

**Comment by itsyoboieltr** [comment]
Do you think there is a way to make it type-safe? @SaltyAom 

After doing this:
```ts
export const app = edenTreaty<App>('', {
  transform: (response) => {
    if (response.error) throw response.error;
    return response.data;
  },
});
```
Returning an error should not be possible anymore, because it is always thrown. Calling the treaty still believes like an error can be returned:

```ts
const res: ({
    data: string[];
    error: null;
} | {
    data: null;
    error: EdenFetchError<number, string>;
}) & {
    status: number;
    response: Response;
    headers: Record<string, string>;
} = await app.api.hello.get();
```

Expected output (ideally, if this is even possible):

```ts
const res: string[] = await app.api.hello.get();
```

**Comment by itsyoboieltr** [comment]
Currently the transform function seems to not run? the requests are not transformed at all. It seems to be buggy both on the type and execution level somehow.

**Comment by itsyoboieltr** [comment]
Upon inspecting the source code it became apparent: it is not transforming the whole response object, only the data property. I guess this was intended by @SaltyAom , but is probably not very intuitive? I expected that it would transform everything returned by Eden Treaty. The current implementation does work seem to work, I just do not know if there is any specific reason why we cannot remove or assign to the other fields?
