### ISSUE TITLE
Unknown Type in Response Data

### ISSUE THREAD

**Issue by Tenzang** [elysiajs/eden#2]
## Summary
The `data` property on EdenTreaty's `.post()` response objects are typed as `unknown` as of the current versions of Eden & Elysia *(0.4.1 & 0.4.10 respectively)*.

To illustrate this I've tried recreating the example CodePen in the [Elysia docs](https://elysiajs.com/patterns/end-to-end-type-safety.html). This works fine with the older Eden & Elysia versions recorded in the `package.json` however upgrading them to the latest version causes the following misbehaviour:
### Expected Behaviour (from example codesandbox)
![expected-behaviour](https://user-images.githubusercontent.com/61134351/234435918-25916d73-fc76-4e82-8199-76c565f90529.png)
### Buggy Behaviour (local machine)
![eden-type-issue](https://user-images.githubusercontent.com/61134351/234433695-795aada5-e495-4754-a4fc-758b5050e5d8.png)

### `package.json`
```json
{
  "name": "hi-elysia",
  "version": "1.0.0",
  "module": "src/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "bun run --hot src/index.ts"
  },
  "dependencies": {
    "@elysiajs/eden": "^0.4.1",
    "elysia": "^0.4.10"
  },
  "devDependencies": {
    "bun-types": "^0.5.0",
    "typescript": "^4.9.4"
  }
}
```
*\*note: swagger has been removed from example which I don't expect would affect the issue*

### `http.ts`
```ts
import { Elysia, t } from "elysia";

// Tips: navigate to /swagger to see the documentation
const app = new Elysia()
	.get("/", () => "Hello Elysia")
	.get("/id/:id", ({ params: { id } }) => id)
	.post("/json", ({ body }) => body, {
		schema: {
			body: t.Object({
				name: t.String(),
			}),
			query: t.Object({
				id: t.String(),
			}),
		},
	})
	.listen(3000);

console.log(
	`Elysia running at http://${app.server?.hostname}:${app.server?.port}`
);

export type App = typeof app;
```

### `eden.ts`
```ts
import { edenTreaty } from "@elysiajs/eden";
import type { App } from "./http";

const api = edenTreaty<App>("http://0.0.0.0:8080");

// Hover over function to see type-definition

// Try hover over the response to see its type
const response1 = await api.index.get();

// Path parameters
api.id["177013"].get();

// Try hover over the response to see its type
// Type inference work even without direct type declaration
const { data } = await api.json.post({
	name: "saltyaom",
	$query: {
		id: "Chiffon",
	},
});

// Type Error
api.json.post({
	// 'name' is not assignable to string
	name: 1,
	// property 'id' is missing
	$query: {},
});
```

**The only differences as far as I can tell between this setup and the example from the docs are the version updates and that swagger has been removed.**

**Comment by Tenzang** [comment]
I've noted that adding specifying the `response` schema in the server will allow `EdenTreaty` to infer the result type. 

I've realized converting non-validated responses to the `unknown` type in the newer version may have been intentional, although I would suggest updating the documentation if that's the case.

**Comment by SaltyAom** [comment]
Right, this is an unexpected bug caused by Elysia 0.4 updating type structure.

Updating Elysia to `^0.4.12` should fix the problem.
