### ISSUE TITLE
How to upload a file using eden treaty?

### ISSUE THREAD

**Issue by terminal-ator** [elysiajs/eden#28]
While the documentation made clear that how to use get and post simple json, there are no example on how to post a file using it, and its not clear on how to approach that. Using formdata as body failed for me. So a better documentation depicting how to make it work would be great.

**Comment by jjhiggz** [comment]
I'm not sure you're supposed to use eden treaty for that. For comparison it doesn't seem like [tRPC supports that](https://github.com/trpc/trpc/discussions/658)

**Comment by SaltyAom** [comment]
You can pass either `File` or `FileList` from value of `<input type='file' >, see [Treaty File Example](https://github.com/elysiajs/eden/blob/main/example/client/src/treaty-file.ts)
