### ISSUE TITLE
[Feature Request] Eden with Elysia instance.

### ISSUE THREAD

**Issue by xantiagoma** [elysiajs/eden#47]
Hi, love your work on Elysia.

Would be great if Eden be used directly with Elysia instance / instance.handle method?
I think I would be useful to have a type-safe client that can be used on the server with RSC, server actions or so.

I imagine something like:
```tsx
import { edenFetch } from '@elysiajs/eden'
import { App } from './server'

const fetch = edenFetch<App>(App)

export default async function ServerComponent() {
  const response = await fetch('/test/:id', {
    params: {
        id: '1895'
    }
});
  const data = await response.json(); // <—- Type inferred
  return (
      <pre>
        {JSON.stringify(data, null, 2)}
      </pre>
  );
}
```

**Comment by timvandam** [comment]
came here to request this, first issue i see is this one :tada: definitely a great feature to have for ssr and the like

**Comment by xantiagoma** [comment]
Closed as it seems It was already included in new Treaty v2 https://elysiajs.com/eden/treaty/config.html#elysia-instance
