### ISSUE TITLE
New prefix option not infers in eden fetch paths

### ISSUE THREAD

**Issue by amirrezamahyari** [elysiajs/eden#7]
new syntax prefix option not infers in elysia eden fetch path

![code](https://github.com/elysiajs/eden/assets/20089037/a68a2cd5-691e-4a35-acb6-b8e634eaa541)

![Screenshot 2023-08-08 at 3 03 43 PM](https://github.com/elysiajs/eden/assets/20089037/1355954c-79bd-4972-a2cc-9beea292db31)

it should be "api/business"

**Comment by brunoeduardodev** [comment]
it's working for me now

**Comment by amirrezamahyari** [comment]
seems fixed, i'll close the issue.
