### ISSUE TITLE
Eden is not recognizing routes when using plugin (router) structure.

### ISSUE THREAD

**Issue by mateusz-kurowskiUG** [elysiajs/eden#75]
admin-router.ts:
```typescript
   const adminRouter = new Elysia({ name: 'Admin', prefix: '/admin' })
    adminRouter.get('/hello', () => 'hello')
    export type adminRouter = typeof adminRouter
    export default adminRouter
 ```
index.ts:
```typescript
    import adminRouter from './admin-router.ts'
    const app = new Elysia({ prefix: '/api' }).use(adminRouter).listen(5000)
```
test.ts:
```typescript
    import type { adminRouter } from '../admin'
    import { treaty } from '@elysiajs/eden'
    const app = treaty<adminRouter>('localhost:5000/')
    const x = await app.api.admin.hello.get() // admin does not exist on type adminRouter
```
Seems like treaty does not work properly using plugin with prefix approach. Does it only work with .group approach or am I doing something wrong?

**Comment by mateusz-kurowskiUG** [comment]
Well, some workaround could be using a new instance of eden for each elysia instance, but...
It works only if we have unique paths, e.g:
Eden works for me:
get.('/a',()=>'a')
post('/b',()=>'b')
But for now it is completely useless if we have routes like:
get.('/',()=>'a')
post('/',()=>'b')

**Comment by kidqueb** [comment]
You need to chain methods on the Elysia instance for them to be recognized.

```diff
const adminRouter = new Elysia({ name: 'Admin', prefix: '/admin' })
-  adminRouter.get('/hello', () => 'hello')
+  .get('/hello', () => 'hello')
export type adminRouter = typeof adminRouter
export default adminRouter```

**Comment by kidqueb** [comment]
@ReyJust I used your snippet and was able to use it in a controller in my project. Would need a reproduction to debug.

```
async function init_database() {
  return { foo: 'bar' }
}

const db = new Elysia({ name: "db" }).decorate("db", await init_database());
```

**Comment by kidqueb** [comment]
There's something going on with `.index` over at https://github.com/elysiajs/eden/issues/71
