### ISSUE TITLE
Treaty Type Mismatch

### ISSUE THREAD

**Issue by QuentinDutot** [elysiajs/eden#9]
Below minimal code:

```
import { Elysia } from 'elysia'
import { edenTreaty } from '@elysiajs/eden'

const app = new Elysia().get('/', () => 'Hi Elysia').listen(3000)

type App = typeof app

const eden = edenTreaty<App>('http://localhost:3000')
```
Produces the error: `Type 'Elysia<"", { ... }>' does not satisfy the constraint 'Elysia<any, { ... }>'.`
And subsequent errors related to the LifeCycleStore type mismatch.

Versions used:
```
"@elysiajs/eden": "^0.6.0",
"@elysiajs/static": "^0.6.0",
"elysia": "^0.6.10"
```

**Comment by SaltyAom** [comment]
Hi, Elysia 0.6.4 introduced an additional generic which caused the Elysia type to mismatch when used with newer versions.

Updating to Eden >= 0.6.1 should fix the problem.

Let me know if this problem still persists after updating Eden version, thanks
